/* Create a staging table to read the raw data in from the CSV files */
create table staging
(
	id	integer,
	city varchar(50),
	jobTitle varchar(100),
	company varchar(100),
	jobLocation varchar(100),
	shortSummary varchar(1000),
	salary numeric(10,2),
	links varchar(100),
	fullSummary varchar(8000)
);

/* Read the Indeed.com CSV into the table */
copy staging(id, city, jobTitle, company, jobLocation, shortSummary,
			salary, links, fullSummary) 
from '/Users/adamdouglas/Downloads/MyData2.csv' DELIMITER ',' CSV HEADER QUOTE '"';

/* Read the ZipRecruiter CSV into the table */
copy staging(id, city, fullSummary)
from '/Users/adamdouglas/Downloads/ZipRecruiter.csv' DELIMITER ',' CSV HEADER QUOTE '"';

/* Table definitions for final normalized forms */
create table city
(cityId smallint generated by default as identity, city varchar(20));

create table jobTitle
(titleId smallint generated by default as identity, jobTitle varchar(100));
													 
create table company
(companyId smallint generated by default as identity, company varchar(100));

create table locations
(locationId smallint generated by default as identity, jobLocation varchar(100));

/* Get our values */
insert into city
(city) select distinct city from staging;

insert into jobTitle
(jobTitle) select distinct jobTitle from staging;							   

insert into company
(company) select distinct company from staging;

insert into locations
(jobLocation) select distinct jobLocation from staging;

/* Create our final table */
create table jobs
(jobID smallint, cityId smallint, jobTitle smallint, companyID smallint,
 locationId smallint, shortSummary varchar(1000), salary numeric(10,2),
 links varchar(100), fullSummary varchar(4000));

/* Populate the table */
insert into jobs
select
	staging.id,
	city.cityId,
	jobTitle.titleId,
	company.companyId,
	locations.locationId,
	staging.shortSummary,
	staging.salary,
	staging.links,
	staging.fullSummary
from staging
join city
on staging.city = city.city
join jobTitle
on staging.jobTitle = jobTitle.jobTitle
join company
on staging.company = company.company
join locations
on staging.jobLocation = locations.jobLocation;

select * from jobs;